import { symbolVariants, symbolWithVariants } from '@/util/symbol-variant'

// Birçok sembolde ortak kullanılan yön isimleri (örn: arrow - both, swap, up, down, left, right) -> arrow-up, arrow-down, arrow-left, arrow-right
const directions = ['up', 'down', 'left', 'right'] as const

const symbols = [
  'account',
  'activate-breakpoints',
  'add',
  'alert',
  'archive',
  'array',
  ...symbolVariants('arrow', [
    'both',
    'swap',
    ...directions,
    ...symbolWithVariants('circle', [...directions], { includeBase: false }),
    ...symbolVariants('small', [...directions]),
  ]),
  ...symbolWithVariants('azure', ['devops']),
  ...symbolWithVariants('beaker', ['stop']),
  ...symbolWithVariants('bell', ['dot', ...symbolWithVariants('slash', ['dot'])]),
  'bold',
  'book',
  'bookmark',
  ...symbolWithVariants('bracket', ['dot', 'error']),
  'briefcase',
  'broadcast',
  'browser',
  'bug',
  'calendar',
  ...symbolVariants('call', ['incoming', 'outgoing']),
  'case-sensitive',
  'checklist',
  ...symbolWithVariants('check', ['all']),
  ...symbolVariants('chevron', [...directions]),
  'chip',
  ...symbolVariants('chrome', ['close', 'maximize', 'minimize', 'restore']),
  ...symbolVariants('circle', [
    'filled',
    ...symbolVariants('large', ['filled', 'outline']),
    'outline',
    'slash',
  ]),
  'circuit-board',
  'clear-all',
  'clippy',
  'clock',
  'clone',
  ...symbolWithVariants('close', ['all', 'dirty']),
  ...symbolWithVariants('cloud', ['download', 'upload']),
  'code',
  'coffee',
  'collapse-all',
  'color-mode',
  'combine',
  ...symbolWithVariants('comment', ['add', 'discussion', 'draft', 'unresolved']),
  'compare-changes',
  ...symbolWithVariants('compass', ['active', 'dot']),
  'console',
  'copilot',
  'copy',
  'credit-card',
  'dash',
  'dashboard',
  'database',
  ...symbolWithVariants('debug', [
    'all',
    ...symbolWithVariants('alt', ['small']),
    ...symbolWithVariants('breakpoint', [
      ...symbolWithVariants('conditional', ['disabled', 'unverified']),
      ...symbolWithVariants('data', ['disabled', 'unverified']),
      'disabled',
      ...symbolWithVariants('function', ['disabled', 'unverified']),
      ...symbolWithVariants('log', ['disabled', 'unverified']),
      'unsupported',
      'unverified',
    ]),
    ...symbolWithVariants('breakpoint', [
      'conditional',
      'data',
      'function',
      ...symbolWithVariants('conditional', ['disabled', 'unverified']),
      ...symbolWithVariants('data', ['disabled', 'unverified']),
      ...symbolWithVariants('function', ['disabled', 'unverified']),
      'unsupported',
      'unverified',
    ]),
    'console',
    ...symbolWithVariants('continue', ['small']),
    'coverage',
    'disconnect',
    'hint',
    'line-by-line',
    'pause',
    'rerun',
    ...symbolWithVariants('restart', ['frame']),
    'reverse-continue',
    ...symbolWithVariants('stackframe', ['active', 'dot', 'focused']),
    'start',
    ...symbolVariants('step', ['back', 'into', 'out', 'over']),
    'stop',
    ...symbolWithVariants('stackframe', ['active', 'dot', 'focused']),
  ]),
  'desktop-download',
  ...symbolVariants('device', ['camera', 'camera-video', 'desktop', 'mobile']),
  ...symbolWithVariants('diff', ['added', 'ignored', 'modified', 'removed', 'renamed']),
  'discard',
  'edit',
  'editor-layout',
  'ellipsis',
  'empty-window',
  'error-small',
  'error',
  'exclude',
  'expand-all',
  'export',
  'extensions',
  ...symbolWithVariants('eye', ['closed', 'unwatch', 'watch']),
  'feedback',
  ...symbolWithVariants('file', [
    'add',
    'binary',
    'code',
    'directory',
    'directory-create',
    'media',
    'pdf',
    'submodule',
    'symlink-directory',
    'symlink-file',
    'text',
    'zip',
  ]),
  'files',
  ...symbolWithVariants('filter', ['filled']),
  'flame',
  ...symbolWithVariants('fold', ['down', 'up']),
  ...symbolWithVariants('folder', ['active', 'library', 'opened']),
  'game',
  'gather',
  'gear',
  'gift',
  ...symbolWithVariants('gist', ['fork', 'new', 'private', 'secret']),
  ...symbolVariants('git', [
    ...symbolWithVariants('branch', ['create', 'delete']),
    'commit',
    'compare',
    'fetch',
    'fork-private',
    'merge',
    ...symbolVariants('pull', [
      ...symbolWithVariants('request', [
        'abandoned',
        'closed',
        'create',
        'draft',
        'new-changes',
        'go-to-changes',
      ]),
    ]),
  ]),
  ...symbolWithVariants('github', ['action', 'alt', 'inverted']),
  'globe',
  'go-to-file',
  'grabber',
  ...symbolWithVariants('graph', ['left', 'line', 'scatter']),
  'gripper',
  'group-by-ref-type',
  'heart',
  'history',
  'home',
  'horizontal-rule',
  'hubot',
  'inbox',
  'indent',
  'info',
  'insert',
  'inspect',
  'issues',
  ...symbolVariants('issue', ['closed', 'draft', 'opened', 'reopened']),
  'italic',
  'jersey',
  'json',
  ...symbolVariants('kebab', ['horizontal', 'vertical']),
  'key',
  'keyboard',
  'law',
  ...symbolWithVariants('layers', ['active', 'dot']),
  ...symbolWithVariants('layout', [
    ...symbolVariants('activitybar', ['left', 'right']),
    'centered',
    'menubar',
    ...symbolWithVariants('panel', ['center', 'justify', 'left', 'right']),
    ...symbolVariants('sidebar', ['left', 'right']),
    'statusbar',
  ]),
  'library',
  'light-bulb',
  ...symbolWithVariants('lightbulb', ['autofix']),
  ...symbolWithVariants('link', ['external']),
  ...symbolVariants('list', ['filter', 'flat', 'ordered', 'selection', 'tree', 'unordered']),
  'live-share',
  'loading',
  'location',
  ...symbolWithVariants('lock', ['small']),
  ...symbolVariants('log', ['in', 'out']),
  'logo-github',
  'magnet',
  ...symbolWithVariants('mail', ['read', 'reply']),
  'mark-github',
  'markdown',
  'megaphone',
  'mention',
  'menu',
  'merge',
  ...symbolWithVariants('mic', ['filled']),
  'microscope',
  'milestone',
  ...symbolWithVariants('mirror', ['private', 'public']),
  'more',
  'mortar-board',
  'move',
  'multiple-windows',
  'music',
  'mute',
  ...symbolVariants('new', ['file', 'folder']),
  'newline',
  'no-newline',
  'note',
  ...symbolWithVariants('notebook', ['template']),
  'octoface',
  'open-preview',
  ...symbolWithVariants('organization', ['filled', 'outline']),
  'output',
  'package',
  'paintcan',
  ...symbolWithVariants('pass', ['filled']),
  'pencil',
  ...symbolWithVariants('person', ['add', 'filled', 'follow', 'outline']),
  'pie-chart',
  'piano',
  'pin',
  ...symbolWithVariants('pinned', ['dirty']),
  ...symbolWithVariants('play', ['circle']),
  'plug',
  'plus',
  'preserve-case',
  'preview',
  ...symbolVariants('primitive', ['dot', 'square']),
  'project',
  'pulse',
  'question',
  'quote',
  'radio-tower',
  'reactions',
  ...symbolWithVariants('record', ['keys', 'small']),
  'redo',
  'references',
  'refresh',
  'regex',
  ...symbolWithVariants('remote', ['explorer']),
  ...symbolWithVariants('remove', ['close']),
  'repl',
  ...symbolWithVariants('replace', ['all']),
  'reply',
  ...symbolWithVariants('repo', [
    'clone',
    'create',
    'delete',
    'force-push',
    'forked',
    'pull',
    'push',
    'sync',
  ]),
  'report',
  'request-changes',
  'rocket',
  ...symbolVariants('root', ['folder', 'folder-opened']),
  'rss',
  'ruby',

  ...symbolWithVariants('run', ['all', 'above', 'below', 'errors']),
  ...symbolWithVariants('save', ['all', 'as']),
  ...symbolVariants('screen', ['full', 'normal']),
  ...symbolWithVariants('search', ['save', 'stop', 'fuzzy']),
  'selection',
  'send',
  ...symbolWithVariants('server', ['environment', 'process']),
  ...symbolWithVariants('settings', ['gear']),
  'shield',
  ...symbolVariants('sign', ['in', 'out']),
  'smiley',
  'snake',
  'sparkle',
  'sort-precedence',
  'source-control',
  ...symbolVariants('split', ['horizontal', 'vertical']),
  'squirrel',
  ...symbolWithVariants('star', ['add', 'delete', 'empty', 'full', 'half']),
  'stop',
  'stop-circle',
  ...symbolVariants('symbol', [
    'array',
    'boolean',
    'class',
    'color',
    'constant',
    'constructor',
    'enum',
    'enum-member',
    'event',
    'field',
    'file',
    'folder',
    'function',
    'interface',
    'key',
    'keyword',
    'method',
    'misc',
    'module',
    'namespace',
    'null',
    'number',
    'numeric',
    'object',
    'operator',
    'package',
    'parameter',
    'property',
    'reference',
    'ruler',
    'snippet',
    'string',
    'struct',
    'structure',
    'text',
    'type-parameter',
    'unit',
    'value',
    'variable',
  ]),
  'sync',
  'sync-ignored',
  ...symbolVariants('tag', ['add', 'remove']),
  'target',
  'tasklist',
  'telescope',
  ...symbolWithVariants('terminal', [
    'bash',
    'cmd',
    'debian',
    'linux',
    'powershell',
    'tmux',
    'ubuntu',
  ]),
  'text-size',
  'three-bars',
  ...symbolWithVariants('thumbsdown', ['filled']),
  ...symbolWithVariants('thumbsup', ['filled']),
  'tools',
  'trash',
  'trashcan',
  ...symbolVariants('triangle', [...directions]),
  'twitter',
  ...symbolVariants('type', [...symbolWithVariants('hierarchy', ['sub', 'super'])]),
  'unfold',
  'ungroup-by-ref-type',
  'unlock',
  'unmute',
  'unverified',
  'variable',
  ...symbolWithVariants('verified', ['filled']),
  'versions',
  ...symbolWithVariants('vm', ['active', 'connect', 'outline', 'running']),
  'vr',
  'warning',
  'watch',
  'whitespace',
  'whole-word',
  'window',
  'word-wrap',
  ...symbolVariants('workspace', ['trusted', 'unknown', 'untrusted']),
  ...symbolWithVariants('wrench', ['subaction']),
  'x',
  'zap',
  ...symbolVariants('zoom', ['in', 'out']),
]
export default symbols
